version: "3"

services:

  # client setup
  client:
    build: ./client
    environment:
      - PORT=${CLIENT_PORT}
    expose:
      - ${CLIENT_PORT}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./client/src:/client/src
      - ./client/public:/client/public
    tty: true
    command: npm run start

  # server setup
  api:
    build: ./backend
    environment:
      - PORT=${API_PORT}
    expose:
      - ${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    working_dir: /backend/cmd/api
    command: go run main.go

  
